//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvCalc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryTable
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> InitialInvestment { get; set; }
        public string TickerSymbol { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> PurchaseShares { get; set; }
        public Nullable<decimal> PercentageDesired { get; set; }
        public Nullable<decimal> TargetSalesPrice { get; set; }
        public Nullable<decimal> InvestmentYield { get; set; }
        public Nullable<decimal> EndBalance { get; set; }
        public Nullable<bool> Action { get; set; }
        public Nullable<bool> Result { get; set; }
    }
}
